PIPELINE_TYPE: 'Voice2Pose'

VOICE2POSE:
  GENERATOR:
    NAME: 'SequenceGeneratorCNN'
    NORM: 'BN'
  POSE_DISCRIMINATOR:
    NAME: 'PoseSequenceDiscriminator'
    LAMBDA_GAN: 0.1
    LEAKY_RELU: True

DATASET:
  NAME: 'GestureDataset'
  ROOT_DIR: 'datasets/speakers'
  HIERARCHICAL_POSE: False

SYS:
  NUM_WORKERS: 16
