PIPELINE_TYPE: 'Voice2Pose'

VOICE2POSE:
  GENERATOR:
    NAME: 'SequenceGeneratorCNN'
    CLIP_CODE:
      DIMENSION: 32
      EXTERNAL_CODE: False

DATASET:
  NAME: 'GestureDataset'
  ROOT_DIR: 'datasets/speakers'
